name: Create Pull Request via GitHub CLI
description: Create a pull request using the GitHub CLI (gh) in workflows

inputs:
  token:
    required: true
    description: GitHub token (typically secrets.GITHUB_TOKEN)

  branch:
    required: true
    description: The name of the branch to push and create the PR from

  base:
    required: true
    description: The base branch to merge into

  title:
    required: true
    description: The title of the pull request

  body:
    required: false
    default: ''
    description: The body of the pull request

runs:
  using: "composite"
  steps:
    - name: Check if PR already exists
      id: pr-check
      run: |
        existing_pr=$(gh pr list \
          --head "${{ inputs.branch }}" \
          --base "${{ inputs.base }}" \
          --state open \
          --json number \
          --jq '.[0].number')

        if [[ -n "$existing_pr" ]]; then
          echo "PR already exists: #$existing_pr"
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "No existing PR found."
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash

    - name: Create Pull Request
      if: steps.pr-check.outputs.exists == 'false'
      run: |
        gh pr create \
          --title "${{ inputs.title }}" \
          --body "${{ inputs.body }}" \
          --base "${{ inputs.base }}" \
          --head "${{ inputs.branch }}" \
          --label "automated"
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
