blank_issues_enabled: false
contact_links:
  # TODO: Update URL field 
  # - name: Documentation
  #   url: https://change.me
  #   about: Check the documentation before creating a new issue.

  - name: Community Discussions
    url: https://github.com/calyjs/calyjs-setup/discussions
    about: For general questions, ideas, or help, please start a discussion instead of opening an issue.

issue_templates:
  - name: Bug Report
    description: Report a reproducible bug in the project
    labels: ["bug"]
    file: bug_report.md

  - name: Feature Request
    description: Suggest a new feature or improvement
    labels: ["enhancement"]
    file: feature_request.md

  - name: Refactor / Code Cleanup
    description: Propose refactoring or code quality improvements
    labels: ["refactor"]
    file: refactor_request.md
