name: Validate Tag Pattern
description: Validates if the GitHub tag matches <project>@<semver> pattern

outputs:
  should-continue:
    description: Whether the workflow should continue or not
    value: ${{ steps.validate.outputs.should-continue }}

runs:
  using: composite
  steps:
    - id: validate
      shell: bash
      run: |
        TAG="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"

        echo "Checking tag: $TAG"

        # Regex: lowercase letters, numbers, hyphens, then @, then x.y.z
        if [[ "$TAG" =~ ^[a-z0-9\-]+@[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Tag $TAG matches pattern: <project>@<semver>"
          echo "should-continue=true" >> "$GITHUB_OUTPUT"
        else
          echo "::warning::Skipping deployment: tag does not match required pattern (<project>@x.y.z)."
          echo "should-continue=false" >> "$GITHUB_OUTPUT"
        fi
