name: Deploy Docs to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      version-bump:
        type: choice
        description: 'Select the version bump to perform.'
        required: true
        default: ''
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

concurrency:
  group: deploy-docs-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  default-branch-check:
    name: "Branch Name check"
    runs-on: ubuntu-latest
    steps:
      - if: github.ref_name != 'master'
        run: |
          echo "Unable to release version for branch $GITHUB_REF"
          exit 1
      - name: "Branch Name check passed"
        run: exit 0
  
  release:
    name: "Release Docs website version"
    needs: default-branch-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HEAD: ${{ github.sha }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup

      - name: Check if website is affected
        id: check_affected
        run: |
          AFFECTED=$(pnpm nx show projects --affected --base='origin/master~1' --head=$HEAD)
          echo "Affected projects: $AFFECTED"
          if [[ "$AFFECTED" != *"website"* ]]; then
            echo "Website not affected. Skipping deploy."
            exit 1
          else
            echo "Website affected. Continue with deploy release process..."
            exit 0
          fi

      - name: "Configure Git"
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          echo "Configured Git user:"
          git config --list --global
        shell: bash

      - name: "Run NX Release script"
        run: node ./scripts/release-docs.js --verbose --version ${{ inputs.version-bump }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-docs:
    name: Deploy Docusaurus Website
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup

      - name: "Configure Git"
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          echo "Configured Git user:"
          git config --list --global
        shell: bash

      - name: Deploy to GitHub Pages
        run: pnpm nx run website:deploy
        shell: bash
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
