name: Deploy Docs to GitHub Pages

on:
  push:
    tags:
      - 'website@*'

jobs:
  deploy:
    name: Deploy Docusaurus Website
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup
        
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Deploy to GitHub Pages
        run: pnpm nx run website:deploy
        shell: bash
        env:
          GIT_USER: ${{ github.actor }}
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
