name: Deploy Website to GitHub Pages 

on:
  push:
    tags:
      - 'website@*'

jobs:
  validate-tag:
    name: Validate Tag Pattern
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.validate.outputs.should-deploy }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Validate tag format
        id: validate
        uses: ./.github/actions/validate-tag

  deploy:
    name: Deploy Docusaurus website
    needs: validate-tag
    if: needs.validate-tag.outputs.should-deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node & pnpm environment
        uses: ./.github/actions/setup

      - name: Configure Git user and GPG signing
        uses: ./.github/actions/git-config
        with:
          gpgPrivId: ${{ secrets.GPG_PRIVATE_KEY }}
          gpgKeyId: ${{ secrets.GPG_KEY_ID }}
        
      - name: Deploy Website to GitHub Pages
        run: pnpm nx run website:deploy
        shell: bash
        env:
          GIT_USER: ${{ github.actor }}
          GIT_PASS: ${{ secrets.GH_TOKEN }}
