name: Deploy Website to GitHub Pages 

on:
  push:
    tags:
      - 'website@*'

jobs:
  validate-tag:
    name: Validate Tag Pattern
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.check-tag.outputs.should-deploy }}
    steps:
      - name: Check if tag pattern matches website@<semver>
        id: check-tag
        run: |
          TAG="${{ github.ref_name }}"
          echo "Checking tag: $TAG"
          if [[ "$TAG" =~ ^website@[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "should-deploy=true" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Skipping deployment: tag does not match required semver pattern (website@x.y.z)."
            echo "should-deploy=false" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    name: Deploy Docusaurus website
    needs: validate-tag
    if: needs.validate-tag.outputs.should-deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node & pnpm environment
        uses: ./.github/actions/setup

      - name: Configure Git user and GPG signing
        uses: ./.github/actions/git-config
        with:
          gpgPrivId: ${{ secrets.GPG_PRIVATE_KEY }}
          gpgKeyId: ${{ secrets.GPG_KEY_ID }}
        
      - name: Deploy Website to GitHub Pages
        run: pnpm nx run website:deploy
        shell: bash
        env:
          GIT_USER: ${{ github.actor }}
          GIT_PASS: ${{ secrets.GH_TOKEN }}
