name: Lint, Test & Build Projects (CI)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]

concurrency:
  group: monorepo-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node & pnpm environment
        uses: ./.github/actions/setup

      - name: Run lint on all projects
        run: pnpm run lint
        shell: bash

  test:
    name: Test Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node & pnpm environment
        uses: ./.github/actions/setup

      - name: Run tests on affected projects
        run: pnpm run test
        shell: bash
  
  build:
    name: Build Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & pnpm environment
        uses: ./.github/actions/setup

      - name: Run build on affected projects
        run: pnpm run build
        shell: bash
