name: Create Docs release tag

on:
  workflow_dispatch:
    inputs:
      version-bump:
        type: choice
        description: 'Select the version bump to perform.'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

concurrency:
  group: release-docs-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  default-branch-check:
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.check-branch.outputs.should-release }}
    steps:
      - name: Check if trigger branch matches default branch
        id: check-branch
        run: |
          BRANCH="${{ github.ref_name }}"
          echo "Checking branch name: $BRANCH"
          if [[ "$BRANCH" == "master" ]]; then
            echo "should-release=true" >> "$GITHUB_OUTPUT"
          else
            echo "Skipping release: trigger branch does not default branch"
            echo "should-release=false" >> "$GITHUB_OUTPUT"
          fi

  release:
    name: "Release Docs website version"
    needs: default-branch-check
    if: needs.default-branch-check.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup

      - name: Check if website is affected
        run: |
          AFFECTED=$(pnpm nx show projects --affected --base='origin/master~1' --head=${{ github.sha }})
          echo "Affected projects: $AFFECTED"
          if [[ "$AFFECTED" != *"website"* ]]; then
            echo "Website not affected. Skipping deploy."
            exit 1
          else
            echo "Website affected. Continue with deploy release process..."
            exit 0
          fi
        
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Run NX Release script
        run: node ./scripts/release-docs.js --verbose --specifier ${{ inputs.version-bump }} --target-branch ${{ vars.RELEASE_BRANCH_NAME }}
 
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create release PR
        uses: ./.github/actions/create-pr
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ vars.RELEASE_BRANCH_NAME }}
          base: master
          title: 'chore(release): version bump'
          body: 'This PR includes version bump and changelog update.'
          commit-message: 'chore(release): version bump'
