name: Create Library release tag

on:
  workflow_dispatch:
    inputs:
      library:
        type: choice
        description: 'Select the library you want to release'
        required: true
        default: 'core'
        options:
          - core
          - utils
          - react
          - affected
      version-bump:
        type: choice
        description: 'Select the version bump to perform.'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

concurrency:
  group: release-lib-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  default-branch-check:
    name: "Default branch check"
    runs-on: ubuntu-latest
    outputs:
      should-continue: ${{ steps.check-branch.outputs.should-continue }}
    steps:
      - name: Check if trigger branch matches default branch
        id: check-branch
        env:
          DEFAULT_BRANCH_NAME: ${{ vars.DEFAULT_BRANCH_NAME }}
        run: |
          set -euo pipefail
          
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Checking branch name: $BRANCH"
          if [[ "$BRANCH" == "$DEFAULT_BRANCH_NAME" ]]; then
            echo "Trigger branch is $BRANCH. Continue with Nx affected check..."
            echo "should-continue=true" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Skipping Docs release: trigger branch is not default"
            echo "should-continue=false" >> "$GITHUB_OUTPUT"
          fi

  detect-affected:
    name: Detect affected libraries
    needs: default-branch-check
    if: needs.default-branch-check.outputs.should-continue == 'true'
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.detect.outputs.should-release }}
      affected-libraries: ${{ steps.detect.outputs.affected-libraries }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup

      - name: Detect affected libraries
        id: detect
        uses: ./.github/actions/detect-affected
        with:
          mode: ${{ inputs.library }}

  release:
    name: "Release library ${{ inputs.library }} version"
    needs: detect-affected
    if: needs.detect-affected.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup

      - name: Configure Git
        uses: ./.github/actions/git-config
        with:
          gpgPrivId: ${{ secrets.GPG_PRIVATE_KEY }}
          gpgKeyId: ${{ secrets.GPG_KEY_ID }}

      - name: Run NX Release script
        run: |
          pnpm run release \
            --specifier ${{ inputs.version-bump }} \
            --target-branch ${{ vars.RELEASE_BRANCH_NAME }} \
            --base-branch ${{ vars.DEFAULT_BRANCH_NAME }} \
            --projects ${{ needs.detect-affected.outputs.affected-libraries }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create release PR
        uses: ./.github/actions/create-pr
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: ${{ vars.RELEASE_BRANCH_NAME }}
          base: ${{ vars.DEFAULT_BRANCH_NAME }}
          title: 'chore(release): add release changes'
          body: 'This PR includes version bump and changelog updates.'
          commit-message: 'chore(release): add release changes'
