name: Create Docs release tag

on:
  workflow_dispatch:
    inputs:
      version-bump:
        type: choice
        description: 'Select the version bump to perform.'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

concurrency:
  group: release-docs-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  default-branch-check:
    name: "Default branch check"
    runs-on: ubuntu-latest
    outputs:
      should-continue: ${{ steps.check-branch.outputs.should-continue }}
    steps:
      - name: Check if trigger branch matches default branch
        id: check-branch
        env:
          DEFAULT_BRANCH_NAME: ${{ vars.DEFAULT_BRANCH_NAME }}
        run: |
          set -euo pipefail
          
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Checking branch name: $BRANCH"
          if [[ "$BRANCH" == "$DEFAULT_BRANCH_NAME" ]]; then
            echo "Trigger branch is $BRANCH. Continue with Nx affected check..."
            echo "should-continue=true" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Skipping Docs release: trigger branch is not default"
            echo "should-continue=false" >> "$GITHUB_OUTPUT"
          fi

  affected-check:
    name: "Docs website changes check"
    runs-on: ubuntu-latest
    needs: default-branch-check
    if: needs.default-branch-check.outputs.should-continue == 'true'
    outputs:
      should-release: ${{ steps.check-affected.outputs.should-release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup
      
      - name: Check if Website app is affected
        id: check-affected
        run: |
          set -euo pipefail

          LAST_TAG=$(git tag --list "website@*" --sort=-creatordate | head -n 1 || true)
          if [[ -n "$LAST_TAG" ]]; then
            echo "Using latest tag for website: $LAST_TAG"
            BASE=$(git rev-list -n 1 "$LAST_TAG")
          else
            echo "No tag found for website. Using initial commit as base."
            BASE=$(git rev-list --max-parents=0 HEAD)
          fi

          HEAD=${GITHUB_SHA:-$(git rev-parse HEAD)}

          AFFECTED=$(pnpm nx show projects --affected --base="$BASE" --head="$HEAD")
          echo "Affected projects: $AFFECTED"

          if [[ "$AFFECTED" != *"website"* ]]; then
            echo "::warning::Website not affected. Skipping release."
            echo "should-release=false" >> "$GITHUB_OUTPUT"
          else
            echo "Website affected. Proceeding with release..."
            echo "should-release=true" >> "$GITHUB_OUTPUT"
          fi

  release:
    name: "Release Docs website version"
    needs: affected-check
    if: needs.affected-check.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup
        
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Run NX Release script
        run: |
          pnpm run release:docs \
            -- --specifier ${{ inputs.version-bump }} \
            --target-branch ${{ vars.RELEASE_BRANCH_NAME }} \
            --base-branch ${{ vars.DEFAULT_BRANCH_NAME }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create release PR
        uses: ./.github/actions/create-pr
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: ${{ vars.RELEASE_BRANCH_NAME }}
          base: ${{ vars.DEFAULT_BRANCH_NAME }}
          title: 'chore(release): add release changes'
          body: 'This PR includes version bump and changelog updates.'
          commit-message: 'chore(release): add release changes'
